# Source for assessed sales ratio: https://files.tax.utah.gov/propertytax/srs/srs202{3-5}.pdf [n+1 for given year]

Davis:
  is_valid: true
  is_wasatch_front: true
  assessed_value_year: 2024
  latest_year_built_with_value: 2023
  latest_year_built_with_oug_set: 2021
  assessment_sales_ratio: 0.9673

Morgan:
  is_valid: true
  is_wasatch_front: false
  assessed_value_year: 2024
  latest_year_built_with_value: 2022
  latest_year_built_with_oug_set: 2023
  assessment_sales_ratio: 0.9748

Salt Lake:
  is_valid: true
  is_wasatch_front: true
  assessed_value_year: 2024
  latest_year_built_with_value: 2023
  latest_year_built_with_oug_set: 2021
  assessment_sales_ratio: 1.0003

Tooele:
  is_valid: true
  is_wasatch_front: false
  assessed_value_year: 2024
  latest_year_built_with_value: 2023
  latest_year_built_with_oug_set: 2023
  assessment_sales_ratio: 0.9763

Utah:
  is_valid: true
  is_wasatch_front: true
  assessed_value_year: 2023
  latest_year_built_with_value: 2022
  latest_year_built_with_oug_set: 2025
  assessment_sales_ratio: 0.9590

Washington:
  is_valid: true
  is_wasatch_front: false
  assessed_value_year: 2022
  latest_year_built_with_value: 2022
  latest_year_built_with_oug_set: 2022
  assessment_sales_ratio: 0.9491

Weber:
  is_valid: true
  is_wasatch_front: true
  assessed_value_year: 2024
  latest_year_built_with_value: 2023
  latest_year_built_with_oug_set: 2022
  assessment_sales_ratio: 0.9450

Box Elder:
  is_valid: false
  is_wasatch_front: false

Summit:
  is_valid: false
  is_wasatch_front: false

Wasatch:
  is_valid: false
  is_wasatch_front: false
